# See versions: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See orbs: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

# See jobs: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Docker executors: https://circleci.com/docs/2.0/executor-types/
    # available CircleCI Docker here: https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: update pip
          command: python3 -m pip install -U pip

      - run:
          name: install dependencies
          command: pip install -r requirements.txt

      - run:
          name: linter flake8
          command: flake8

      - run:
          name: Run tests
          command: pytest
  docker-build-and-push:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t oc-lettings-vf:v1 .
      - run:
          name: Dockerhub login
          command: docker login --username $DOCKERHUB_LOGIN --password $DOCKERHUB_PASSWORD
      - run:
          name: Tag docker image
          command: docker tag oc-lettings-vf:v1 $DOCKERHUB_LOGIN/oc-lettings:$CIRCLE_SHA1
      - run:
          name: push image to dockerhub
          command: docker push $DOCKERHUB_LOGIN/oc-lettings:$CIRCLE_SHA1
  heroku-push:
    docker:
      - image: cimg/python:.10.2
    steps:
      - checkout
      - run:
          name: Install heroku CLI
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run
          name: Login Heroku
          command: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run
          name: Heroku push
          command: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push web
      - run
          name: Heroku release
          command: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web


# See workflow: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  oc-lettings-deployment: # This is the name of the workflow
    jobs:
      - build-and-test
      - docker-build-and-push:
          context:
            - circleci_context

          # filters:
          #   branches:
          #     only:
          #       - master
          requires:
            - build-and-test
      - heroku-push:
          context:
            - circleci_context

          # filters:
          #   branches:
          #     only:
          #       - master
          requires:
            - build-and-test
            - docker-build-and-push