# See versions: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See orbs: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

# See jobs: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Docker executors: https://circleci.com/docs/2.0/executor-types/
    # available CircleCI Docker here: https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: update pip
          command: python3 -m pip install -U pip

      - run:
          name: install dependencies
          command: pip install -r requirements.txt

      - run:
          name: linter flake8
          command: flake8

      - run:
          name: Run tests
          command: pytest
  docker-build-and-push:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: test
          command: echo "just a test"


# See workflow: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow
    jobs:
      - build-and-test
      - docker-build-and-push:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
